Repository jshmrtn/hygeia, pull requests merged in 2021-11, with the labels that each got.

#811 Autotracing - Symptom start date updated problematic dates counting
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
Labels: cla-signed

#813 Autotracing - Employer step added class / division
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/auto_tracing_context/auto_tracing/occupation.ex
  lib/hygeia/auto_tracing_context/auto_tracing/school_visit.ex
  lib/hygeia/organisation_context/affiliation.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/employer.ex
  lib/hygeia_web/live/auto_tracing_live/employer.sface
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/division_live/choose.ex
  lib/hygeia_web/live/division_live/choose.sface
  lib/hygeia_web/live/person_live/base_data.ex
  lib/hygeia_web/live/person_live/base_data.sface
  mix.exs
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211103105723_affiliation_unknown_organisation_and_divisions.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#820 Fix Possible Index Submission Delete (#819)
  lib/hygeia_web/live/auto_tracing_live/contact_persons.sface
  lib/hygeia_web/live/possible_index_submission_live/index.sface
  lib/hygeia_web/live/possible_index_submission_live/submissions_table.ex
  lib/hygeia_web/live/possible_index_submission_live/submissions_table.sface
Labels: cla-signed

#822 Autotracing employer step: fixed missing checkbox when removing known organisation
  lib/hygeia/auto_tracing_context/auto_tracing/occupation.ex
  lib/hygeia/auto_tracing_context/auto_tracing/school_visit.ex
  lib/hygeia_web/live/auto_tracing_live/employer.sface
Labels: cla-signed

#823 Autotracing Resolve Problems - prevents occupations from jumping around when resolving unknown organisations
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
Labels: cla-signed

#825 Autotracing employer step - division picker improvements
  lib/hygeia_web/live/auto_tracing_live/employer.sface
  lib/hygeia_web/live/division_live/choose.ex
  lib/hygeia_web/live/division_live/choose.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#826 Simplifies employer step for AT.
  lib/hygeia_web/live/auto_tracing_live/employer.sface
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
Labels: cla-signed

#837 Autotracing - ResolveProblems Affiliation Fix
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
Labels: cla-signed

#840 Fix Auto Tracing Test Sorting
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
Labels: bug, cla-signed

#838 Improve Auto Tracing Resolve Problems Affiliation / Division Rendering
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
Labels: cla-signed

#858 Text change for PrematureRelease view
  lib/hygeia_web/live/premature_release_live/create.ex
  lib/hygeia_web/live/premature_release_live/create.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#867 Remove Auto Tracing No Reaction when Person completes tracing process
  lib/hygeia_web/live/auto_tracing_live/end.ex
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: enhancement, cla-signed

#868 Remove Email Recipient Name to avoid leaking Authorization Data
  lib/hygeia/communication_context/email.ex
Labels: bug, cla-signed

#869 Auto Tracing Swiss Covid App Description
  lib/hygeia_web/live/auto_tracing_live/covid_app.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#870 Check if Gettext up-to-date in CI
  .github/workflows/ci.yml
Labels: enhancement

#872 Add Case Filter for complete Auto Tracing
  lib/hygeia_web/live/case_live/index.ex
  lib/hygeia_web/live/case_live/index.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia_web/live/case_live_test.exs
Labels: enhancement, cla-signed

#879 Changes for the infection place view on transmission
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/transmission.sface
  lib/hygeia_web/live/transmission_live/infection_place.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia_web/live/transmission_live_test.exs
Labels: cla-signed

#433 Refactoring create possible index
  assets/js/app.js
  assets/js/bsn.js
  config/prod.exs
  config/runtime.exs
  config/test.exs
  lib/hygeia/case_context.ex
  lib/hygeia/communication_context.ex
  lib/hygeia/organisation_context/affiliation.ex
  lib/hygeia_web/helpers/changeset.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/helpers/form_step.ex
  lib/hygeia_web/helpers/person.ex
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index.scss
  lib/hygeia_web/live/case_live/create_possible_index.sface
  lib/hygeia_web/live/case_live/create_possible_index/case_snippet.ex
  lib/hygeia_web/live/case_live/create_possible_index/case_snippet.sface
  lib/hygeia_web/live/case_live/create_possible_index/create_person_schema.ex
  lib/hygeia_web/live/case_live/create_possible_index/create_schema.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_administration.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_administration.scss
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_administration.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_contact_methods.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_contact_methods.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.sface
  lib/hygeia_web/live/case_live/create_possible_index/person_card.ex
  lib/hygeia_web/live/case_live/create_possible_index/person_card.scss
  lib/hygeia_web/live/case_live/create_possible_index/person_card.sface
  lib/hygeia_web/live/case_live/create_possible_index/person_snippet.ex
  lib/hygeia_web/live/case_live/create_possible_index/person_snippet.sface
  lib/hygeia_web/live/case_live/create_possible_index/service.ex
  lib/hygeia_web/live/case_live/navigation.sface
  lib/hygeia_web/live/case_live/person_create_table.ex
  lib/hygeia_web/live/case_live/person_create_table.scss
  lib/hygeia_web/live/case_live/person_create_table.sface
  lib/hygeia_web/live/case_live/transmissions.sface
  lib/hygeia_web/live/person_live/base_data.sface
  lib/hygeia_web/live/possible_index_submission_live/create.ex
  lib/hygeia_web/live/possible_index_submission_live/create.sface
  lib/hygeia_web/live/possible_index_submission_live/show.sface
  lib/hygeia_web/live/search.sface
  lib/hygeia_web/router.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/errors.po
  test/hygeia_web/live/case_live_test.exs
  test/support/case_live_test_helper.ex
  test/support/fixtures.ex
Labels: cla-signed

#880 Add return_url and case link to TransmissionView
  lib/hygeia_web/live/case_live/choose.ex
  lib/hygeia_web/live/case_live/choose.sface
  lib/hygeia_web/live/case_live/transmissions.sface
Labels: cla-signed

#881 Possible index submission - assign case supervisors from propagator to possible index submission
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_administration.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.ex
Labels: cla-signed

#886 Autotracing Recreate PossibleIndexSubmission problem with new submission
  lib/hygeia_web/live/possible_index_submission_live/create.ex
Labels: cla-signed

#891 Fix handle_event Issues
  lib/hygeia_web.ex
  lib/hygeia_web/live/case_live/protocol.sface
  lib/hygeia_web/live/init/discard_empy_handle_event.ex
  lib/hygeia_web/live/transmission_live/show.ex
Labels: bug, cla-signed

#895 Various Bugfixes
  lib/hygeia_web/live/case_live/choose.sface
  lib/hygeia_web/live/help_live/index.sface
  lib/hygeia_web/live/person_live/header.ex
  lib/hygeia_web/live/person_live/vaccination.sface
  lib/hygeia_web/router.ex
Labels: bug

#896 Increate Threshold for Phase Date Inconsitent Auto Tracing Problem
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
Labels: enhancement

#899 Add LiveView Sentry Breadcrumbs
  lib/hygeia_web.ex
  lib/hygeia_web/live/init/context.ex
  lib/hygeia_web/live/init/sentry.ex
Labels: enhancement, cla-signed

#898 Autotracing - Standalone Visits
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/auto_tracing_context/auto_tracing/occupation.ex
  lib/hygeia/auto_tracing_context/auto_tracing/organisation_visit.ex
  lib/hygeia/auto_tracing_context/auto_tracing/school_visit/reason.ex
  lib/hygeia/auto_tracing_context/auto_tracing/step.ex
  lib/hygeia/case_context/person.ex
  lib/hygeia/organisation_context.ex
  lib/hygeia/organisation_context/affiliation.ex
  lib/hygeia/organisation_context/division.ex
  lib/hygeia/organisation_context/organisation.ex
  lib/hygeia/organisation_context/visit.ex
  lib/hygeia/organisation_context/visit/reason.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/auto_tracing.ex
  lib/hygeia_web/live/auto_tracing_live/contact_methods.ex
  lib/hygeia_web/live/auto_tracing_live/employer.ex
  lib/hygeia_web/live/auto_tracing_live/employer.sface
  lib/hygeia_web/live/auto_tracing_live/header.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/visits.ex
  lib/hygeia_web/live/auto_tracing_live/visits.sface
  lib/hygeia_web/live/division_live/index.sface
  lib/hygeia_web/live/organisation_live/index.sface
  lib/hygeia_web/live/person_live/base_data.ex
  lib/hygeia_web/live/person_live/header.ex
  lib/hygeia_web/live/person_live/header.sface
  lib/hygeia_web/live/visit_live/create.ex
  lib/hygeia_web/live/visit_live/create.sface
  lib/hygeia_web/live/visit_live/form.ex
  lib/hygeia_web/live/visit_live/form.sface
  lib/hygeia_web/live/visit_live/index.ex
  lib/hygeia_web/live/visit_live/index.sface
  lib/hygeia_web/live/visit_live/show.ex
  lib/hygeia_web/live/visit_live/show.sface
  lib/hygeia_web/router.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211117230115_create_visits.exs
  test/hygeia/organisation_context_test.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
  test/hygeia_web/live/visit_live_test.exs
  test/support/fixtures.ex
Labels: enhancement, cla-signed

#900 Visits - added desc sorting to visits
  lib/hygeia_web/live/visit_live/form.sface
  lib/hygeia_web/live/visit_live/index.ex
  lib/hygeia_web/live/visit_live/index.sface
Labels: cla-signed

#901 Create Possible Index - Fix stuck checkbox
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
Labels: cla-signed

#904 Visits - Fixed translations and removed uneccessary text in page title
  lib/hygeia_web/live/visit_live/index.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#909 Visits - Visit points to case instead of person
  lib/hygeia/case_context/case.ex
  lib/hygeia/case_context/person.ex
  lib/hygeia/organisation_context.ex
  lib/hygeia/organisation_context/visit.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/visits.ex
  lib/hygeia_web/live/case_live/navigation.ex
  lib/hygeia_web/live/case_live/navigation.sface
  lib/hygeia_web/live/person_live/header.ex
  lib/hygeia_web/live/person_live/header.sface
  lib/hygeia_web/live/visit_live/create.ex
  lib/hygeia_web/live/visit_live/create.sface
  lib/hygeia_web/live/visit_live/index.ex
  lib/hygeia_web/live/visit_live/index.sface
  lib/hygeia_web/live/visit_live/show.ex
  lib/hygeia_web/live/visit_live/show.sface
  lib/hygeia_web/router.ex
  priv/repo/migrations/20211117230115_create_visits.exs
  test/hygeia/organisation_context_test.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
  test/hygeia_web/live/visit_live_test.exs
  test/support/fixtures.ex
Labels: cla-signed

#917 Autotracing - Employer step changed disabling text for visit related occupations
  lib/hygeia_web/live/auto_tracing_live/employer.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#911 Create Possible Index - Duplicate/suggestion UI remake
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/person_snippet.ex
  lib/hygeia_web/live/case_live/create_possible_index/person_snippet.sface
  lib/hygeia_web/live/case_live/create_possible_index/suggestions.ex
  lib/hygeia_web/live/case_live/create_possible_index/suggestions.scss
  lib/hygeia_web/live/case_live/create_possible_index/suggestions.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#910 Create Possible Index - Merged administration and contact methods steps
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.scss
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_administration.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_contact_methods.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.sface
  lib/hygeia_web/live/case_live/create_possible_index/service.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia_web/live/case_live_test.exs
  test/support/case_live_test_helper.ex
Labels: cla-signed

#933 Create Possible Index - Modify button text and link existing person fullname to case
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.sface
  lib/hygeia_web/live/case_live/create_possible_index/person_card.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#935 Create Possible Index - Copy tenant in search/create when infection type is own household and in person if possible index submission
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.ex
  test/hygeia_web/live/case_live_test.exs
Labels: cla-signed

#937 Refactor Case / Person Suggestions into reusable Component
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/suggestions.ex
  lib/hygeia_web/live/case_live/suggestions.scss
  lib/hygeia_web/live/case_live/suggestions.sface
  lib/hygeia_web/live/person_live/base_data.sface
  lib/hygeia_web/live/person_live/create.ex
  lib/hygeia_web/live/person_live/create.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#941 Create Person Form Separate Component
  lib/hygeia_web/live/person_live/base_data.scss
  lib/hygeia_web/live/person_live/create.ex
  lib/hygeia_web/live/person_live/create.sface
  lib/hygeia_web/live/person_live/create_form.ex
  lib/hygeia_web/live/person_live/create_form.sface
Labels: cla-signed
