Repository jshmrtn/hygeia, pull requests merged in 2021-12, with the labels that each got.

#940 Create Possible Index - Change new person card UI
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.ex
  lib/hygeia_web/live/case_live/create_possible_index/suggestions.ex
  lib/hygeia_web/live/case_live/create_possible_index/suggestions.scss
  lib/hygeia_web/live/case_live/create_possible_index/suggestions.sface
  lib/hygeia_web/live/case_live/suggestions.ex
  lib/hygeia_web/live/case_live/suggestions.scss
  lib/hygeia_web/live/case_live/suggestions.sface
  lib/hygeia_web/live/person_live/create_form.ex
  lib/hygeia_web/live/person_live/create_form.sface
  lib/hygeia_web/router.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia_web/live/case_live_test.exs
  test/support/case_live_test_helper.ex
Labels: cla-signed

#944 Create Possible Index - Flash message hotfix
  lib/hygeia_web/live/case_live/create_possible_index.ex
Labels: cla-signed

#945 Create Possible Index - Fixed landline and other contact methods breaking notifications logic
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.ex
Labels: cla-signed

#946 Create Possible Index - Fixed missing case status field in actions step
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.sface
  lib/hygeia_web/live/case_live/create_possible_index/person_card.ex
  lib/hygeia_web/live/case_live/create_possible_index/person_card.sface
Labels: cla-signed

#947 Create Possible Index - Fixed error when changing case status to done or canceled
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
Labels: cla-signed

#948 Limit Notification Tray Count
  lib/hygeia/notification_context.ex
  lib/hygeia_web/live/notification/tray.ex
  lib/hygeia_web/live/notification/tray.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#951 Adds various UI/UX fixes for possible index submissions
  lib/hygeia_web/live/case_live/create_possible_index/case_snippet.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.sface
  lib/hygeia_web/live/case_live/create_possible_index/person_card.ex
  lib/hygeia_web/live/case_live/create_possible_index/person_card.scss
  lib/hygeia_web/live/case_live/create_possible_index/person_card.sface
  lib/hygeia_web/live/person_live/base_data.scss
Labels: cla-signed

#932 Expose Test Reference in UI
  lib/hygeia_web/live/test_live/form.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed, high-priority

#934 Vaccination Failure Export
  lib/hygeia/case_context.ex
  lib/hygeia/case_context/case/clinical.ex
  lib/hygeia/case_context/case/clinical/symptom.ex
  lib/hygeia/case_context/case/clinical/test_reason.ex
  lib/hygeia_web.ex
  lib/hygeia_web/controllers/tenant_controller.ex
  lib/hygeia_web/helpers/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.sface
  lib/hygeia_web/live/case_live/base_data.sface
  lib/hygeia_web/live/tenant_live/export.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia/case_context_test.exs
Labels: enhancement, cla-signed, high-priority

#953 Person Vaccination - Fix jumping dates due to html date max option
  lib/hygeia/case_context/person/vaccination.ex
  lib/hygeia/case_context/possible_index_submission.ex
  lib/hygeia_web/live/person_live/vaccination.ex
  lib/hygeia_web/live/person_live/vaccination.sface
  lib/hygeia_web/live/possible_index_submission_live/create.sface
  priv/gettext/de/LC_MESSAGES/errors.po
  priv/gettext/errors.pot
  priv/gettext/fr/LC_MESSAGES/errors.po
  priv/gettext/it/LC_MESSAGES/errors.po
Labels: bug, cla-signed, high-priority

#952 Autotracing - Travel step with high risk travel
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/auto_tracing_context/auto_tracing/problem.ex
  lib/hygeia/auto_tracing_context/auto_tracing/step.ex
  lib/hygeia/auto_tracing_context/auto_tracing/travel.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/auto_tracing.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/header.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/transmission.sface
  lib/hygeia_web/live/auto_tracing_live/travel.ex
  lib/hygeia_web/live/auto_tracing_live/travel.sface
  lib/hygeia_web/live/auto_tracing_live/visits.ex
  lib/hygeia_web/router.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211201143102_add_travels_to_auto_tracings.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: enhancement, cla-signed, high-priority

#939 Removing AT InconsistentPhaseDate, changing phase end calculation
  lib/hygeia/auto_tracing_context/auto_tracing/problem.ex
  lib/hygeia/case_context/case/phase.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.sface
  lib/hygeia_web/live/auto_tracing_live/header.sface
  lib/hygeia_web/live/auto_tracing_live/hints.ex
  lib/hygeia_web/live/auto_tracing_live/hints.sface
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211130150556_remove_phase_date_inconsistent_from_autotracing_problems.exs
  test/support/fixtures.ex
Labels: enhancement, cla-signed, high-priority

#955 Adds new propagator link to summary for possible index submissions.
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/summary.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#956 Person - Duplicate detection bug with query bindings not cast to varchar
  lib/hygeia/case_context.ex
  lib/hygeia/case_context/possible_index_submission.ex
Labels: bug, cla-signed

#957 Autotracing - Resolve problems travel section show country name insted of code
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
Labels: enhancement, cla-signed

#958 Vaccination Export - Fixed bug when vaccination done is nil caused by failed sql cast to boolean
  lib/hygeia/case_context.ex
Labels: cla-signed

#960 Migrate Auto Tracing Step Flights Properly
  lib/hygeia.ex
  priv/repo/migrations/20210719122928_tenant_location.exs
  priv/repo/migrations/20210914093248_tenant_contact_method.exs
  priv/repo/migrations/20211117230115_create_visits.exs
  priv/repo/migrations/20211130150556_remove_phase_date_inconsistent_from_autotracing_problems.exs
  priv/repo/migrations/20211202171922_auto_tracing_travel_migration.exs
Labels: bug, cla-signed

#965 Breakthrough Infection Export Fix
  lib/hygeia/case_context.ex
  test/hygeia/case_context_test.exs
Labels: bug, cla-signed

#964 Remove min/max from all DateInput
  lib/hygeia.ex
  lib/hygeia/auto_tracing_context/auto_tracing/organisation_visit.ex
  lib/hygeia/auto_tracing_context/auto_tracing/travel.ex
  lib/hygeia/case_context/case/clinical.ex
  lib/hygeia/case_context/person.ex
  lib/hygeia/case_context/possible_index_submission.ex
  lib/hygeia/case_context/transmission.ex
  lib/hygeia/helpers/calendar.ex
  lib/hygeia/organisation_context/visit.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.sface
  lib/hygeia_web/live/auto_tracing_live/travel.sface
  lib/hygeia_web/live/auto_tracing_live/visits.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_transmission.sface
  lib/hygeia_web/live/possible_index_submission_live/create.sface
  lib/hygeia_web/live/visit_live/form.sface
Labels: bug, cla-signed, high-priority

#967 Setup Elixir 1.13 in CI (test only, building with 1.12)
  .github/workflows/ci.yml
  .tool-versions
  assets/package-lock.json
Labels: cla-signed

#968 Use Elixir Surface Formatter Plugin
  .formatter.exs
  .github/workflows/ci.yml
  README.md
Labels: enhancement, cla-signed

#962 Check Permission for SMS / Email Create before send
  lib/hygeia_web/live/case_live/navigation.sface
Labels: bug, cla-signed

#969 Switch to Elixir 1.3 hexpm/bob images
  .github/workflows/ci.yml
  Dockerfile
  mix.exs
Labels: enhancement, cla-signed

#988 Migrate inserted_at Date for Old Cases
  priv/repo/migrations/20211208094932_case_phases_inserted_at_complete.exs
Labels: bug, cla-signed, high-priority

#989 Improve Sentry Context Contents
  lib/hygeia_web/live/init/auth.ex
  lib/hygeia_web/live/init/context.ex
  lib/hygeia_web/plug/check_and_refresh_authentication.ex
Labels: bug, enhancement, cla-signed, high-priority

#1004 Create Possible Index - Set case status to done on possible index submission imports
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_people.ex
  lib/hygeia_web/live/case_live/create_possible_index/service.ex
  test/hygeia_web/live/case_live_test.exs
Labels: cla-signed

#993 Adding CheckConstraint to affiliation changeset
  lib/hygeia/organisation_context/affiliation.ex
Labels: cla-signed

#1012 Fix vaccination filters
  lib/hygeia_web/live/case_live/index.ex
  lib/hygeia_web/live/case_live/index.sface
  lib/hygeia_web/live/person_live/index.ex
Labels: cla-signed

#1006 Autotracing - Clinical step phase start greater than phase end bug
  lib/hygeia/auto_tracing_context/auto_tracing/problem.ex
  lib/hygeia/case_context/case/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.sface
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/case_live/base_data.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211220095509_add_auto_tracing_problem_phase_ends_in_the_past.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#1055 Autotracing - Clinical step set phase quarantine order to false if phase ends in the past
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#1050 Case - Changed text explaining when a person can leave quarantine early
  lib/hygeia_web/live/person_overview_live/index.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1051 Autotracing - End step added link to covid certificate page
  lib/hygeia_web/live/auto_tracing_live/end.ex
  lib/hygeia_web/live/auto_tracing_live/end.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1053 Autotracing - No reaction problem solving resets no reaction problem timer
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
Labels: cla-signed

#1054 Export - Added person email field to hygeia extended fields
  lib/hygeia/case_context.ex
  test/hygeia/case_context_test.exs
Labels: cla-signed

#1056 Create Possible Index - fix date bug when skipping invalid define transmission step
  lib/hygeia_web/live/case_live/create_possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.ex
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed
