Repository jshmrtn/hygeia, pull requests merged in 2021-04, with the labels that each got.

#22 Setup Coveralls
  .github/workflows/ci.yml
Labels: cla-signed, enhancement

#32 issue #12 - Field Name for fulltext is not defined
  apps/hygeia_web/lib/hygeia_web/live/version_live/change.ex
Labels: cla-signed

#37 Update Deps
  apps/hygeia/mix.exs
  apps/hygeia_web/assets/js/chart.hook.js
  apps/hygeia_web/assets/js/shuffle.js
  apps/hygeia_web/assets/package-lock.json
  apps/hygeia_web/assets/package.json
  apps/hygeia_web/lib/hygeia_web/live/chart.ex
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/daily_statistics.sface
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/timeline.sface
  mix.lock
Labels: cla-signed, enhancement

#38 issue #211 - Abteilung/Klasse suchen bricht ab
  apps/hygeia/lib/hygeia/organisation_context.ex
Labels: cla-signed

#39 issue gitlab#203 - Vaccination Jab Dates Add Fix when nil
  apps/hygeia/lib/hygeia/case_context/person/vaccination.ex
  apps/hygeia_web/lib/hygeia_web/live/person_live/base_data.ex
Labels: cla-signed

#50 Affiltiation Ordering / Pagination Fix
  apps/hygeia_web/lib/hygeia_web/live/affiliation_live/index.ex
Labels: bug, cla-signed

#29 Viewer logging
  apps/hygeia_web/lib/hygeia_web/controllers/pdf_controller.ex
  apps/hygeia_web/lib/hygeia_web/endpoint.ex
  apps/hygeia_web/lib/hygeia_web/helpers/viewer_logging.ex
  apps/hygeia_web/lib/hygeia_web/live/affiliation_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/choose.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/person_create_table.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/protocol.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/transmission_table.sface
  apps/hygeia_web/lib/hygeia_web/live/notification/case_assignee.sface
  apps/hygeia_web/lib/hygeia_web/live/notification/email_send_failed.sface
  apps/hygeia_web/lib/hygeia_web/live/organisation_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/person_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/person_live/choose.sface
  apps/hygeia_web/lib/hygeia_web/live/person_live/header.sface
  apps/hygeia_web/lib/hygeia_web/live/person_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/possible_index_submission_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/possible_index_submission_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/record_view.ex
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/header.sface
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/version_live/table.sface
  apps/hygeia_web/lib/hygeia_web/live_view.ex
Labels: cla-signed

#53 Override Default Tracer to Administration in Create Case Views
  apps/hygeia_web/lib/hygeia_web/live/case_live/create/create_schema.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_index.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.ex
Labels: cla-signed, enhancement

#54 Explicit Quarantine / Isolation Orders
  apps/hygeia/lib/hygeia/case_context.ex
  apps/hygeia/lib/hygeia/case_context/case/phase.ex
  apps/hygeia/priv/repo/migrations/20210415111909_quarantine_order.exs
  apps/hygeia/test/hygeia/case_context_test.exs
  apps/hygeia/test/hygeia/statistics_context_test.exs
  apps/hygeia/test/support/fixtures.ex
  apps/hygeia_web/lib/hygeia_web/helpers/field_name.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_index/create_schema.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/create_schema.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.sface
Labels: cla-signed, enhancement

#57 Fixes translations for new quarantine/isolation ordering. gitlab#193
  apps/hygeia_gettext/priv/gettext/de/LC_MESSAGES/default.po
  apps/hygeia_gettext/priv/gettext/default.pot
  apps/hygeia_gettext/priv/gettext/en/LC_MESSAGES/default.po
Labels: cla-signed

#58 issue gitlab#187 - Organisation Delete
  apps/hygeia/lib/hygeia/organisation_context.ex
  apps/hygeia/lib/hygeia/organisation_context/division.ex
  apps/hygeia/lib/hygeia/organisation_context/organisation.ex
  apps/hygeia/lib/hygeia/statistics_context.ex
  apps/hygeia/lib/hygeia/statistics_context/active_cases_per_day_and_organisation.ex
  apps/hygeia/priv/repo/migrations/20210416111804_organisation_delete_cascade.exs
  apps/hygeia/test/hygeia/statistics_context_test.exs
  apps/hygeia_gettext/priv/gettext/de/LC_MESSAGES/default.po
  apps/hygeia_gettext/priv/gettext/default.pot
  apps/hygeia_gettext/priv/gettext/en/LC_MESSAGES/default.po
  apps/hygeia_web/lib/hygeia_web/live/division_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/division_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/organisation_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/organisation_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/organisation_table.sface
Labels: cla-signed

#68 Allow Phase Edit
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia/lib/hygeia/case_context/case/phase.ex
  apps/hygeia/lib/hygeia/case_context/case/phase/type.ex
  apps/hygeia_gettext/priv/gettext/de/LC_MESSAGES/default.po
  apps/hygeia_gettext/priv/gettext/default.pot
  apps/hygeia_gettext/priv/gettext/en/LC_MESSAGES/default.po
  apps/hygeia_web/lib/hygeia_web/helpers/changeset.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.sface
Labels: cla-signed, enhancement

#69 Update Deps
  apps/hygeia_web/mix.exs
  mix.lock
Labels: cla-signed, enhancement

#70 Remove Related Organisations
  apps/hygeia/lib/hygeia/case_context.ex
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia/lib/hygeia/helpers/versioning.ex
  apps/hygeia/lib/hygeia/organisation_context.ex
  apps/hygeia/lib/hygeia/organisation_context/organisation.ex
  apps/hygeia/priv/repo/migrations/20210419130620_remove_case_related_organisation.exs
  apps/hygeia/priv/repo/structure.sql
  apps/hygeia/test/hygeia/case_context_test.exs
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/related_organisations/related_organisations.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/related_organisations/related_organisations.scss
  apps/hygeia_web/lib/hygeia_web/live/case_live/related_organisations/related_organisations.sface
Labels: cla-signed, enhancement

#71 Do not try to send notification emails to users without authorization
  apps/hygeia/lib/hygeia/notification_context.ex
Labels: bug, cla-signed

#56 Zitadel API Update
  apps/hygeia/lib/hygeia/jobs/user_sync.ex
  apps/hygeia/mix.exs
  config/runtime.exs
  mix.lock
Labels: cla-signed, enhancement

#82 Case Status Validation
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia/test/hygeia/case_context_test.exs
  apps/hygeia/test/support/fixtures.ex
Labels: cla-signed, enhancement

#72 Viewer Logging Persistence (gitlab#174)
  .dialyzer_ignore.exs
  apps/hygeia/lib/hygeia/audit_context.ex
  apps/hygeia/lib/hygeia/audit_context/resource_view.ex
  apps/hygeia/lib/hygeia/ecto_type/ip.ex
  apps/hygeia/lib/hygeia/jobs/supervisor.ex
  apps/hygeia/lib/hygeia/jobs/viewer_log_persitence/job.ex
  apps/hygeia/lib/hygeia/jobs/viewer_log_persitence/supervisor.ex
  apps/hygeia/priv/repo/migrations/20210419154442_create_resource_views.exs
  apps/hygeia_web/lib/hygeia_web/controllers/pdf_controller.ex
  apps/hygeia_web/lib/hygeia_web/endpoint.ex
  apps/hygeia_web/lib/hygeia_web/helpers/viewer_logging.ex
  apps/hygeia_web/lib/hygeia_web/live/record_view.ex
  apps/hygeia_web/lib/hygeia_web/live_view.ex
Labels: cla-signed, enhancement

#89 Set Default Tracer / Supervisor of Possible Index same as Index
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/transmissions.sface
Labels: cla-signed, enhancement

#92 Removes contact information from index view.
  apps/hygeia_web/lib/hygeia_web/live/home_live/index.sface
Labels: cla-signed

#93 Case Phase Create Improvements
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia/test/hygeia/case_context_test.exs
  apps/hygeia/test/support/fixtures.ex
  apps/hygeia_gettext/priv/gettext/de/LC_MESSAGES/default.po
  apps/hygeia_gettext/priv/gettext/default.pot
  apps/hygeia_gettext/priv/gettext/en/LC_MESSAGES/default.po
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/create_schema.ex
Labels: cla-signed, enhancement

#106 Fix Test Stage if Coveralls is down
  .github/workflows/ci.yml
Labels: cla-signed, enhancement

#108 Do not double-validate Cases
  apps/hygeia/lib/hygeia/case_context.ex
Labels: bug, cla-signed

#109 Allow 1 Day Phase Overlap
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/create_schema.ex
Labels: bug, cla-signed

#110 Replaces date-fns with luxon for statistics date localization.
  apps/hygeia_web/assets/js/chart.hook.js
  apps/hygeia_web/assets/package-lock.json
  apps/hygeia_web/assets/package.json
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/timeline.sface
Labels: cla-signed, enhancement

#111 Disable automated close email on phase create
  apps/hygeia_gettext/priv/gettext/de/LC_MESSAGES/default.po
  apps/hygeia_gettext/priv/gettext/default.pot
  apps/hygeia_gettext/priv/gettext/en/LC_MESSAGES/default.po
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.sface
Labels: cla-signed, enhancement

#118 Do not show Cases in Create Index Merge when not authorized
  apps/hygeia_web/lib/hygeia_web/live/case_live/person_create_table.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/person_create_table.sface
Labels: bug, cla-signed

#126 Improve Dialyzer Types for UUIDs
  apps/hygeia/lib/hygeia/case_context.ex
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia/lib/hygeia/case_context/case/hospitalization.ex
  apps/hygeia/lib/hygeia/case_context/note.ex
  apps/hygeia/lib/hygeia/case_context/person.ex
  apps/hygeia/lib/hygeia/case_context/possible_index_submission.ex
  apps/hygeia/lib/hygeia/case_context/transmission.ex
  apps/hygeia/lib/hygeia/communication_context.ex
  apps/hygeia/lib/hygeia/communication_context/email.ex
  apps/hygeia/lib/hygeia/communication_context/sms.ex
  apps/hygeia/lib/hygeia/notification_context.ex
  apps/hygeia/lib/hygeia/notification_context/notification.ex
  apps/hygeia/lib/hygeia/notification_context/notification/case_assignee.ex
  apps/hygeia/lib/hygeia/notification_context/notification/email_send_failed.ex
  apps/hygeia/lib/hygeia/organisation_context.ex
  apps/hygeia/lib/hygeia/organisation_context/affiliation.ex
  apps/hygeia/lib/hygeia/organisation_context/division.ex
  apps/hygeia/lib/hygeia/organisation_context/organisation.ex
  apps/hygeia/lib/hygeia/organisation_context/position.ex
  apps/hygeia/lib/hygeia/statistics_context/active_cases_complexity_per_day.ex
  apps/hygeia/lib/hygeia/statistics_context/active_cases_per_day_and_organisation.ex
  apps/hygeia/lib/hygeia/statistics_context/active_hospitalization_cases_per_day.ex
  apps/hygeia/lib/hygeia/statistics_context/active_infection_place_cases_per_day.ex
  apps/hygeia/lib/hygeia/statistics_context/active_isolation_cases_per_day.ex
  apps/hygeia/lib/hygeia/statistics_context/active_quarantine_cases_per_day.ex
  apps/hygeia/lib/hygeia/statistics_context/cumulative_index_case_end_reasons.ex
  apps/hygeia/lib/hygeia/statistics_context/cumulative_possible_index_case_end_reasons.ex
  apps/hygeia/lib/hygeia/statistics_context/new_cases_per_day.ex
  apps/hygeia/lib/hygeia/statistics_context/transmission_country_cases_per_day.ex
  apps/hygeia/lib/hygeia/system_message_context.ex
  apps/hygeia/lib/hygeia/system_message_context/system_message.ex
  apps/hygeia/lib/hygeia/tenant_context.ex
  apps/hygeia/lib/hygeia/tenant_context/sedex_export.ex
  apps/hygeia/lib/hygeia/tenant_context/tenant.ex
  apps/hygeia/lib/hygeia/user_context.ex
  apps/hygeia/lib/hygeia/user_context/grant.ex
  apps/hygeia/lib/hygeia/user_context/user.ex
  apps/hygeia/lib/hygeia/version_context.ex
  apps/hygeia/lib/hygeia/version_context/version.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create/create_schema.ex
  apps/hygeia_web/lib/hygeia_web/live/system_message_live/create.ex
  apps/hygeia_web/lib/hygeia_web/live/system_message_live/show.ex
Labels: cla-signed, enhancement

#127 Fix Ecto Setup for Test
  apps/hygeia/mix.exs
Labels: cla-signed, enhancement
