Repository jshmrtn/hygeia, pull requests merged in 2021-05, with the labels that each got.

#150 Update Deps
  apps/hygeia_web/lib/hygeia_web/live/case_live/person_create_table.sface
  apps/hygeia_web/lib/hygeia_web/live/date_input.ex
  apps/hygeia_web/lib/hygeia_web/live/date_time_local_input.ex
  apps/hygeia_web/lib/hygeia_web/live/field_label.ex
  mix.lock
Labels: cla-signed, enhancement

#168 Isolation Confirmation Start Date consider Test Date
  apps/hygeia_pdf_confirmation/lib/hygeia_pdf_confirmation/helpers/confirmation_dates.ex
Labels: cla-signed, enhancement

#187 Check PDF Availability
  apps/hygeia/lib/hygeia/case_context/case/phase.ex
  apps/hygeia_web/lib/hygeia_web/controllers/pdf_controller.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/navigation.sface
Labels: cla-signed

#188 Update CLDR Session Plugs
  apps/hygeia_web/lib/hygeia_web.ex
  apps/hygeia_web/lib/hygeia_web/router.ex
Labels: cla-signed

#189 Statistics Validate Date
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/daily_statistics.ex
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/export.ex
  apps/hygeia_web/lib/hygeia_web/live/statistics_live/timeline.ex
Labels: cla-signed

#190 Catch Paginator Param Pase Error
  apps/hygeia_web/lib/hygeia_web/invalid_pagination_params_error.ex
  apps/hygeia_web/lib/hygeia_web/live/affiliation_live/index.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/index.ex
  apps/hygeia_web/lib/hygeia_web/live/division_live/index.ex
  apps/hygeia_web/lib/hygeia_web/live/organisation_live/index.ex
  apps/hygeia_web/lib/hygeia_web/live/person_live/index.ex
  apps/hygeia_web/lib/hygeia_web/live/sedex_export_live/index.ex
Labels: cla-signed

#191 Fix duplicate ID for Affiliation
  apps/hygeia_web/lib/hygeia_web/live/affiliation_live/index.sface
Labels: cla-signed

#199 Liste Abteilungen/Klassen alphabetisch sortieren
  apps/hygeia_web/lib/hygeia_web/live/division_live/index.ex
Labels: cla-signed

#204 Activity Mapping Improvements
  apps/hygeia/lib/hygeia/case_context.ex
  apps/hygeia/lib/hygeia/case_context/case.ex
  apps/hygeia/lib/hygeia/case_context/case/status.ex
  apps/hygeia/lib/hygeia/case_context/possible_index_submission.ex
  apps/hygeia/lib/hygeia/case_context/transmission.ex
  apps/hygeia/lib/hygeia/case_context/transmission/infection_place.ex
  apps/hygeia/priv/repo/migrations/20210521094209_activity_mapping_fix.exs
  apps/hygeia/priv/repo/seeds.exs
  apps/hygeia/priv/repo/structure.sql
  apps/hygeia/test/hygeia/case_context_test.exs
  apps/hygeia/test/support/fixtures.ex
  apps/hygeia_gettext/priv/gettext/de/LC_MESSAGES/default.po
  apps/hygeia_gettext/priv/gettext/default.pot
  apps/hygeia_gettext/priv/gettext/en/LC_MESSAGES/default.po
  apps/hygeia_web/lib/hygeia_web/helpers/case.ex
  apps/hygeia_web/lib/hygeia_web/helpers/field_name.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/base_data.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_phase_modal.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index.sface
  apps/hygeia_web/lib/hygeia_web/live/case_live/create_possible_index/create_schema.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/index.ex
  apps/hygeia_web/lib/hygeia_web/live/case_live/index.sface
  apps/hygeia_web/lib/hygeia_web/live/possible_index_submission_live/create.ex
  apps/hygeia_web/lib/hygeia_web/live/possible_index_submission_live/create.sface
  apps/hygeia_web/lib/hygeia_web/live/possible_index_submission_live/show.ex
  apps/hygeia_web/lib/hygeia_web/live/possible_index_submission_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/create.ex
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/create.sface
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/infection_place.ex
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/infection_place.sface
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/show.ex
  apps/hygeia_web/lib/hygeia_web/live/transmission_live/show.sface
  apps/hygeia_web/lib/hygeia_web/live/version_live/change.ex
  apps/hygeia_web/test/hygeia_web/live/transmission_live_test.exs
Labels: cla-signed, enhancement

#205 BAG MED export quar_yn Fix
  apps/hygeia/lib/hygeia/case_context.ex
  apps/hygeia/test/hygeia/case_context_test.exs
Labels: bug, cla-signed

#213 Update Deps
  apps/hygeia_web/lib/hygeia_web/live/lock.ex
  apps/hygeia_web/lib/hygeia_web/live/tenant_live/show.sface
  apps/hygeia_web/lib/hygeia_web/router.ex
  apps/hygeia_web/lib/hygeia_web/templates/layout/live.html.leex
  apps/hygeia_web/mix.exs
  mix.lock
Labels: cla-signed, enhancement

#216 Affiliation Filter Fix
  apps/hygeia_web/lib/hygeia_web/live/affiliation_live/index.ex
Labels: bug, cla-signed

#218 Update surface
  apps/hygeia_web/mix.exs
  mix.lock
Labels: cla-signed
