Repository jshmrtn/hygeia, pull requests merged in 2022-02, with the labels that each got.

#1183 Phase in Past AutoTracing Handling
  lib/hygeia/auto_tracing_context/auto_tracing/problem.ex
  lib/hygeia/case_context/case.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20220131141414_remove_phase_ends_in_the_past_from_auto_tracing_problems.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#1190 one auto tracing per case bugfix
  priv/repo/migrations/20220201141946_fix_one_auto_tracing_per_case.exs
Labels: cla-signed

#1195 Add Config to Disable Contact person Quarantine in Auto Tracing
  config/config.exs
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/auto_tracing_context/auto_tracing/step.ex
  lib/hygeia/jobs/detect_no_reaction_cases.ex
  lib/hygeia_web/helpers/auto_tracing.ex
  lib/hygeia_web/live/auto_tracing_live/address.ex
  lib/hygeia_web/live/auto_tracing_live/auto_tracing.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/contact_methods.ex
  lib/hygeia_web/live/auto_tracing_live/contact_persons.ex
  lib/hygeia_web/live/auto_tracing_live/covid_app.ex
  lib/hygeia_web/live/auto_tracing_live/employer.ex
  lib/hygeia_web/live/auto_tracing_live/end.ex
  lib/hygeia_web/live/auto_tracing_live/end.sface
  lib/hygeia_web/live/auto_tracing_live/header.ex
  lib/hygeia_web/live/auto_tracing_live/header.sface
  lib/hygeia_web/live/auto_tracing_live/start.ex
  lib/hygeia_web/live/auto_tracing_live/transmission.ex
  lib/hygeia_web/live/auto_tracing_live/travel.ex
  lib/hygeia_web/live/auto_tracing_live/vaccination.ex
  lib/hygeia_web/live/auto_tracing_live/visits.ex
  lib/hygeia_web/live/person_overview_live/index.sface
  lib/hygeia_web/live/possible_index_submission_live/index.ex
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#1201 Filter Case List Auto Tracing Complete correctly
  lib/hygeia_web/live/case_live/index.ex
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: bug, cla-signed

#1219 Use Case InsertedAt only as Fallback for Case Dates
  lib/hygeia/case_context/case.ex
Labels: bug, cla-signed

#1220 Shorten Auto Tracing Invite SMS Text
  lib/hygeia/auto_tracing_context/auto_tracing_communication.ex
  lib/hygeia/import_context/planner/action/save.ex
  lib/hygeia_web/live/case_live/navigation.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#1230 SMS-EmailTextChange
  lib/hygeia/jobs/send_case_closed_email.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1237 Removed text inviting to submit contact persons from sms template
  assets/package-lock.json
  lib/hygeia_web/helpers/confirmation.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1260 Inbox: Phase aus der Vergangenheit angewählt
  lib/hygeia/case_context/case.ex
  lib/hygeia/case_context/case/phase.ex
  lib/hygeia/import_context/planner/generator/ism_2021_06_11.ex
  test/hygeia/import_context/planner/generator/ism_2021_06_11_test_test.exs
  test/hygeia/import_context/planner/generator/ism_2021_06_11_test_test_ism_ids.exs
Labels: cla-signed

#1263 Inbox - fix migration for multi to multi imports to rows
  priv/repo/migrations/20220215190419_create_row_links.exs
Labels: cla-signed

#1275 Inbox Check Dates for Rows with Predecessor (#1228)
  lib/hygeia/import_context/planner/generator/ism_2021_06_11.ex
  test/hygeia/import_context/planner/generator/ism_2021_06_11_test_test_ism_ids.exs
Labels: cla-signed
