Repository jshmrtn/hygeia, pull requests merged in 2022-01, with the labels that each got.

#1068 changes default Quarantine Duration to 7 days instead of 10
  lib/hygeia/case_context/case/phase/possible_index.ex
  lib/hygeia_web/live/case_live/create_possible_index/service.ex
Labels: enhancement, cla-signed

#1069 Adapt Possible Index Submission Text
  lib/hygeia/case_context/case.ex
  lib/hygeia_web/live/auto_tracing_live/contact_persons.ex
  lib/hygeia_web/live/auto_tracing_live/contact_persons.sface
  lib/hygeia_web/live/possible_index_submission_live/create.ex
  lib/hygeia_web/live/possible_index_submission_live/create.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#1070 changes texts for premature release and deprecated negative tests
  lib/hygeia/case_context/premature_release.ex
  lib/hygeia/case_context/premature_release/reason.ex
  lib/hygeia_web/live/person_overview_live/index.sface
  lib/hygeia_web/live/premature_release_live/create.ex
  lib/hygeia_web/live/premature_release_live/create.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#1071 Premature release text test - add italian and french translations
  lib/hygeia_web/live/person_overview_live/index.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1072 Update CI
  .github/workflows/branch_main.yml
  .github/workflows/ci.yml
  .github/workflows/part_build.yml
  .github/workflows/part_dependabot.yml
  .github/workflows/part_deploy.yml
  .github/workflows/part_docs.yml
  .github/workflows/part_release.yml
  .github/workflows/part_test.yml
  .github/workflows/part_tool_versioning.yml
  .github/workflows/pr.yml
  .github/workflows/tag-beta.yml
  .github/workflows/tag-stable.yml
  .github/workflows/weekly.yml
  README.md
Labels: cla-signed

#1073 Update Lincese Change Date
  LICENSE
Labels: enhancement, cla-signed

#1074 Minor Fixes for AT Transmissions
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/transmission.ex
  priv/gettext/de/LC_MESSAGES/default.po
Labels: enhancement, cla-signed

#1046 Autotracing - Transmission step raise problem on new transmission
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/auto_tracing_context/auto_tracing/problem.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/transmission.ex
  lib/hygeia_web/live/auto_tracing_live/transmission.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211223101132_add_possible_transmission_to_auto_tracings.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#1044 Autotracing - Travel step extended
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/auto_tracing_context/auto_tracing/travel.ex
  lib/hygeia/risk_country_context.ex
  lib/hygeia/risk_country_context/risk_country.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/travel.ex
  lib/hygeia_web/live/auto_tracing_live/travel.sface
  lib/hygeia_web/live/case_live/choose.sface
  lib/hygeia_web/live/header.sface
  lib/hygeia_web/live/risk_country_live/index.ex
  lib/hygeia_web/live/risk_country_live/index.scss
  lib/hygeia_web/live/risk_country_live/index.sface
  lib/hygeia_web/live/transmission_live/create.sface
  lib/hygeia_web/router.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20220103114333_create_risk_countries.exs
  priv/repo/migrations/20220103114334_migrate_auto_tracing_travel.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
  test/hygeia_web/live/risk_country_live_test.exs
  test/support/fixtures.ex
Labels: cla-signed

#1083 Autotracing - Travel Step prevent rising problem when no risk travels selected
  lib/hygeia_web/live/auto_tracing_live/travel.ex
Labels: cla-signed

#1096 Transmission Type Fix
  lib/hygeia/case_context/transmission.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.ex
  lib/hygeia_web/live/auto_tracing_live/resolve_problems.sface
  lib/hygeia_web/live/auto_tracing_live/transmission.ex
  lib/hygeia_web/live/auto_tracing_live/transmission.sface
  lib/hygeia_web/live/case_live/create_possible_index/service.ex
  lib/hygeia_web/live/case_live/transmission_table.ex
  lib/hygeia_web/live/case_live/transmission_table.sface
  lib/hygeia_web/live/transmission_live/create.sface
  lib/hygeia_web/live/transmission_live/show.ex
  lib/hygeia_web/live/transmission_live/show.sface
  priv/repo/migrations/20220111093904_transmission_type.exs
  test/hygeia/case_context_test.exs
  test/hygeia_web/live/transmission_live_test.exs
  test/support/fixtures.ex
Labels: cla-signed

#1098 Quarantine length changed in SMS, E-Mail confirmation
  lib/hygeia_web/helpers/confirmation.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1101 Autotracing - Travel Step risk travels new widget
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/travel.ex
  lib/hygeia_web/live/auto_tracing_live/travel.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia_web/live/auto_tracing_live_test.exs
Labels: cla-signed

#1078 Vaccination Refactoring & Statistics
  config/config.exs
  lib/hygeia.ex
  lib/hygeia/case_context.ex
  lib/hygeia/case_context/person.ex
  lib/hygeia/case_context/person/vaccination.ex
  lib/hygeia/case_context/person/vaccination_shot.ex
  lib/hygeia/case_context/person/vaccination_shot/vaccine_type.ex
  lib/hygeia/case_context/person/vaccination_shot/validity.ex
  lib/hygeia/ecto_type/date_range.ex
  lib/hygeia/jobs/notification_reminder.ex
  lib/hygeia/jobs/supervisor.ex
  lib/hygeia/statistics_context.ex
  lib/hygeia/statistics_context/vaccination_breakthroughs_per_day.ex
  lib/hygeia_web/controllers/statistics_controller.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/auto_tracing_live/vaccination.ex
  lib/hygeia_web/live/auto_tracing_live/vaccination.sface
  lib/hygeia_web/live/case_live/index.ex
  lib/hygeia_web/live/person_live/base_data.ex
  lib/hygeia_web/live/person_live/base_data.scss
  lib/hygeia_web/live/person_live/base_data.sface
  lib/hygeia_web/live/person_live/index.ex
  lib/hygeia_web/live/person_live/vaccination.ex
  lib/hygeia_web/live/person_live/vaccination.scss
  lib/hygeia_web/live/person_live/vaccination.sface
  lib/hygeia_web/live/statistics_live/daily_statistics.ex
  lib/hygeia_web/live/statistics_live/daily_statistics.sface
  lib/hygeia_web/live/statistics_live/export.sface
  lib/hygeia_web/live/statistics_live/timeline.ex
  lib/hygeia_web/live/statistics_live/timeline.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20211230121753_create_vaccination_shots.exs
  priv/repo/seeds.exs
  test/hygeia/case_context_test.exs
  test/hygeia/statistics_context_test.exs
  test/hygeia_web/live/auto_tracing_live_test.exs
  test/hygeia_web/live/person_live_test.exs
Labels: cla-signed

#1106 Text changes in the premature release view
  lib/hygeia_web/live/premature_release_live/create.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1115 New ISM import antigen test kind
  lib/hygeia/import_context/planner/generator/ism_2021_06_11.ex
Labels: cla-signed

#1123 Vaccine Validity Improvements
  lib/hygeia/ecto_type/date_range.ex
  priv/repo/migrations/20211230121753_create_vaccination_shots.exs
  priv/repo/migrations/20220117182843_vaccination_validity_case_influence.exs
  test/hygeia/case_context_test.exs
  test/support/fixtures.ex
Labels: enhancement, cla-signed

#1124 Show Error with disabled JavaScript and prevent Person Login
  assets/css/app.scss
  assets/js/app.js
  lib/hygeia_web/live/auth_live/login.sface
  lib/hygeia_web/live/home_live/index.ex
  lib/hygeia_web/templates/layout/live.html.heex
  lib/hygeia_web/templates/layout/root.html.heex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1108 Phase ordering when creating new phase
  lib/hygeia_web/live/case_live/create_phase_modal.ex
  lib/hygeia_web/live/case_live/create_phase_modal.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1105 Tests: Testdatum ändern
  lib/hygeia_web/helpers/field_name.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1093 Order Case Dates for Auto Tracing Cotact Person Order
  lib/hygeia/case_context/case.ex
Labels: cla-signed

#1087 Show info for test reasons in AutoTracing
  lib/hygeia_web/live/auto_tracing_live/clinical.ex
  lib/hygeia_web/live/auto_tracing_live/clinical.sface
Labels: cla-signed

#1039 Person Login Rate Limit
  lib/hygeia/application.ex
  lib/hygeia/login_rate_limiter.ex
  lib/hygeia/login_rate_limiter/worker.ex
  lib/hygeia_web/live/auth_live/login.ex
  lib/hygeia_web/live/auth_live/login.sface
  mix.exs
  mix.lock
  test/hygeia/login_rate_limiter_test.exs
Labels: enhancement, cla-signed

#1084 Allow disabling Premature Release
  lib/hygeia/case_context/case/phase.ex
  lib/hygeia/case_context/case/phase/possible_index.ex
  lib/hygeia/case_context/premature_release/disabled_reason.ex
  lib/hygeia_web/helpers/field_name.ex
  lib/hygeia_web/live/case_live/base_data.ex
  lib/hygeia_web/live/case_live/base_data.sface
  lib/hygeia_web/live/person_overview_live/index.sface
  lib/hygeia_web/live/premature_release_live/create.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20220106132952_create_premature_release_disabled_reason.exs
  test/hygeia_web/live/case_live_test.exs
Labels: cla-signed

#1111 Use ICU Gettext Interpolation
  .formatter.exs
  lib/hygeia/auto_tracing_context/auto_tracing_communication.ex
  lib/hygeia/jobs/notification_reminder.ex
  lib/hygeia/jobs/send_case_closed_email.ex
  lib/hygeia/jobs/send_emails.ex
  lib/hygeia_cldr.ex
  lib/hygeia_gettext.ex
  lib/hygeia_web.ex
  lib/hygeia_web/helpers/case.ex
  lib/hygeia_web/helpers/confirmation.ex
  lib/hygeia_web/live/auto_tracing_live/contact_persons.sface
  lib/hygeia_web/live/auto_tracing_live/end.sface
  lib/hygeia_web/live/auto_tracing_live/travel.ex
  lib/hygeia_web/live/auto_tracing_live/travel.sface
  lib/hygeia_web/live/case_live/base_data.sface
  lib/hygeia_web/live/case_live/create_phase_modal.sface
  lib/hygeia_web/live/case_live/create_possible_index/form_step/define_action.ex
  lib/hygeia_web/live/case_live/suggestions.sface
  lib/hygeia_web/live/case_live/transmission_table.sface
  lib/hygeia_web/live/division_live/create.ex
  lib/hygeia_web/live/division_live/create.sface
  lib/hygeia_web/live/home_live/index.sface
  lib/hygeia_web/live/notification/tray.sface
  lib/hygeia_web/live/organisation_live/create.sface
  lib/hygeia_web/live/organisation_live/show.sface
  lib/hygeia_web/live/pagination.ex
  lib/hygeia_web/live/person_live/base_data.sface
  lib/hygeia_web/live/person_live/vaccination.ex
  lib/hygeia_web/live/person_live/vaccination.sface
  lib/hygeia_web/live/person_overview_live/index.sface
  lib/hygeia_web/live/possible_index_submission_live/create.sface
  lib/hygeia_web/live/row_live/apply.sface
  lib/hygeia_web/live/statistics_live/header.sface
  lib/hygeia_web/views/error_helpers.ex
  mix.exs
  mix.lock
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/de/LC_MESSAGES/errors.po
  priv/gettext/default.pot
  priv/gettext/errors.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/fr/LC_MESSAGES/errors.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/errors.po
Labels: cla-signed

#1135 Update Vaccination Text
  lib/hygeia_web/live/person_live/base_data.sface
  lib/hygeia_web/live/person_live/vaccination_validity.ex
  lib/hygeia_web/live/person_live/vaccination_validity.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/repo/migrations/20220117182843_vaccination_validity_case_influence.exs
Labels: cla-signed

#1136 Vaccination Validity Fix for internal Convalescence
  priv/repo/migrations/20220117182843_vaccination_validity_case_influence.exs
  test/hygeia/case_context_test.exs
Labels: cla-signed

#1148 Fix translations after ICU message format changes
  lib/hygeia_web/live/case_live/create_phase_modal.sface
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
Labels: cla-signed

#1145 login_lock_remaining_interval not found bug
  lib/hygeia_web/live/auth_live/login.ex
Labels: cla-signed

#1170 Fix Protocol Performance Issues (#1164)
  lib/hygeia/case_context.ex
Labels: bug, cla-signed

#1172 Update phoenix_live_view to released version
  mix.exs
  mix.lock
Labels: cla-signed

#1177 Case status done not possible with unresolved AT problems
  lib/hygeia/auto_tracing_context/auto_tracing.ex
  lib/hygeia/case_context/case.ex
  lib/hygeia_web/live/case_live/base_data.ex
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  test/hygeia/case_context_test.exs
Labels: cla-signed
